<?php
$tracks=[

"INSERT INTO tracks VALUES(1,1)",
"INSERT INTO tracks VALUES(2,2)",
"INSERT INTO tracks VALUES(2,3)",
"INSERT INTO tracks VALUES(11,1)",
"INSERT INTO tracks VALUES(10,10)",
"INSERT INTO tracks VALUES(2,2)","INSERT INTO tracks VALUES(1,10)",
"INSERT INTO tracks VALUES(4,4)","INSERT INTO tracks VALUES(1,1)",
"INSERT INTO tracks VALUES(3,7)","INSERT INTO tracks VALUES(8,8)",
"INSERT INTO tracks VALUES(10,1)","INSERT INTO tracks VALUES(1,11)",
"INSERT INTO tracks VALUES(5,5)",
"INSERT INTO tracks VALUES(7,7)","INSERT INTO tracks VALUES(8,8)",
"INSERT INTO tracks VALUES(1,1)","INSERT INTO tracks VALUES(1,1)",
"INSERT INTO tracks VALUES(11,14)"];

?>